name: flutter_conf_latam
description: The Flutter Conf Latam web page.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: 3.29.0

dependencies:
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.1.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  responsive_builder: 0.7.1
  rive: ^0.13.20
  shared_preferences: ^2.5.3
  timezone: ^0.10.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/sponsors/
    - assets/anims/
  fonts:
    - family: FlutterConfLatamIcons
      fonts:
        - asset: assets/iconfonts/FlutterConfLatamIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100