name: flutter_conf_latam
description: The Flutter Conf Latam web page.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: 3.38.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.4
  collection: ^1.19.1
  equatable: ^2.0.7
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.3+1
  flutter_layout_grid: ^2.0.8
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.2
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+8
  rive: ^0.13.20
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  vector_graphics: ^1.1.18

dev_dependencies:
  build_runner: ^2.10.3
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  vector_graphics_compiler: ^1.1.19
  very_good_analysis: ^10.0.0

flutter_gen:
  output: lib/styles/generated/
  line_length: 80

  integrations:
    flutter_svg: false
    image: false
    rive: false

  fonts:
    enabled: false

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/launcher/fcl_launcher_logo.png"
    background_color: "#042B59"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/files/
    - assets/images/
    - assets/images/about/
    - assets/images/contact/
    - assets/images/collaborations/
    - assets/images/features/
    - assets/images/gallery/
    - assets/images/icons/
    - assets/images/novelties/
    - assets/images/sponsors/
    - assets/images/venue/
    - assets/markdown/

  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta/Recoleta-Black.ttf
          weight: 900
        - asset: assets/fonts/Recoleta/Recoleta-Bold.ttf
          weight: 700
        - asset: assets/fonts/Recoleta/Recoleta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Recoleta/Recoleta-Medium.ttf
          weight: 500
        - asset: assets/fonts/Recoleta/Recoleta-Regular.ttf
          weight: 400
        - asset: assets/fonts/Recoleta/Recoleta-Light.ttf
          weight: 300
        - asset: assets/fonts/Recoleta/Recoleta-Thin.ttf
          weight: 100
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100